version: '3.2'

services:

  postgres:
    image: postgres
    container_name: database
    build:
      context: .
      dockerfile: Dockerfile-Postgres
    volumes:
      - "./data/database:/var/lib/postgresql/data"
    env_file:
      - ./config/.env

  redis:
    image: redis
    container_name: cache
    build:
      context: .
      dockerfile: Dockerfile-Redis
    volumes:
      - "./data/redis:/data"

  nginx:
    image: nginx
    container_name: proxy
    build:
      context: .
      dockerfile: Dockerfile-Nginx
    ports:
     - "80:80"
    depends_on:
      - django
    env_file:
      - ./config/.env
    volumes:
      - "./config/nginx.dev.conf:/etc/nginx/conf.d/app.conf"
      - "./data/static:/static"
      - "./log:/var/log/nginx"

    #command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

  django:
    build:
      context: .
      dockerfile: Dockerfile-Django
    image: django
    container_name: web
    command: ./bin/start_django.sh
    volumes:
      - "./app:/src"
      - "./data/static:/static"
      - "./log:/log"
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    env_file:
      - ./config/.env

volumes:
  app:
  data:
  log:
