FROM python:3.6
ENV PYTHONUNBUFFERED 1

#ENV C_FORCE_ROOT true # intentionally kept it commented

ENV APP_USER user
ENV APP_ROOT /src

RUN groupadd -r ${APP_USER} && useradd -r -m --home-dir ${APP_ROOT} -s /usr/sbin/nologin -g ${APP_USER} ${APP_USER}

ADD requirements.txt ${APP_ROOT}
RUN pip install -r ${APP_ROOT}/requirements.txt

USER ${APP_USER}
ADD ./src/ ${APP_ROOT}
WORKDIR ${APP_ROOT}/${PROJECT_NAME}

CMD celery -A ${PROJECT_NAME} worker
#CMD pwd
