version: '3'

services:

  database:
    image: postgres
    container_name: database

  web:
    build: .
    image: django
    container_name: web

    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src:/code
    ports:
      - "8000:8000"
    depends_on:
      - database