version: '3.2'

services:

  database:
    image: postgres
    container_name: database
    volumes:
      - "./data:/var/lib/postgresql/data"
    env_file:
      - ./config/.env

  web:
    build: .
    image: django
    container_name: web
    command: ./bin/start_django.sh
    volumes:
      - "./src:/src"
    ports:
      - "8000:8000"
    depends_on:
      - database
    env_file:
      - ./config/.env

volumes:
  data:
  app: