version: '3.2'

services:

  database:
    image: postgres
    container_name: database
    volumes:
      - "./data/database:/var/lib/postgresql/data"
    env_file:
      - ./config/.env

  redis:
    image: redis
    container_name: cache
    build:
      context: .
      dockerfile: Dockerfile-Redis
    volumes:
      - "./data/redis:/data"

  web:
    build:
      context: .
      dockerfile: Dockerfile-Django
    image: django
    container_name: web
    command: ./bin/start_django.sh
    volumes:
      - "./app:/src"
      - "./data/log:/log"
    ports:
      - "8000:8000"
    depends_on:
      - database
      - redis
    env_file:
      - ./config/.env

volumes:
  data:
  app: